language: node_js
node_js: '10'

script:
  - yarn lint
  - yarn build
  - yarn test-ci
# keep the npm cache around to speed up installs
cache:
  yarn: true
deploy:
  provider: npm
  email:
    secure: hfE9fPhfyKgnF9pkFBeOE4JOfFaNJqGVkAqvTw+G8lwCnstuEVnzVzzzRExb71RwH+XRuTY/CAmDGH5uvHlM05YdKiQ7h5AppYFp+zEDZJqetjaLRCxFvnOEgf5y3t4ULsJ9bU3idQHZZCPd/Ybh+4JC3UrAXU12p++f8yrYbdL3KH4J1rhsM50U3p6ZcDxKx87jT2a8jDVp7udCttMyDtuSlte/FBpL9JIyB2bfkABYgKxEd0Nh42t8UYf65kIqYT+t+g1y3T1KDyI2oP7wB/zRj2WNmdTU4TL2J9SxZNvNnuXfjdK9ytQfB65PKDVvwYtl4HLRCXNDPGKlyAjcyaO6uPl67/EMLYtIE/yvjSIiScayCSuQ+yJCskmS5lZNUrp52B2yQb+p07QFMlh61LeVysMYIYNZ77sViofZNARH+vZvRHmxFC+ROx/JcCc4436UDWohbpI8uz9pCfuRjgS86sVzRZMrMzQUa0y2U6a4As5etmPcrYJ4cwFwL7UVzoUicWQaIfy0uo2eHp0vgMU7Ll0W3i8BstmxLidftOkfd76z6sJJZpqtGzADTi03tgC1gVlmkRben/AEuQ2rCyXotyOqSsMa6BeF022ujWxNTrpr2HFDOeFOkz8yKrhlEikIp4JUQUp4hkig5UzzBRwSFh7QPtmcnWKd+79kQRI=
  api_key:
    secure: H9qt/7nEzOi17xZQ0xdhZSJw4jnntIlHQOxLmcIsspiUG2KUzaAAWqHkFKxactF++pZEaLSbsLjQbc8IvCpHrn0NlE7qTYLbW9iXpealM0zGryBXly7aLDfXKXbs7hZ4BglTCP/pPNiOu5zOhLczVbfbQvYD5D2QU3VE0JIrq0UrnRG81sou706T7E1L72bLuo6giQEi4LgXDnrczfcBahLG6V996ZqigrwDeKdiHFhaZ/rRcftnCAm6LCm7cgI+wLgMSmHGhGgBo01uw4dZlknKl+hl59/BYZU2RPknJF81Kii8jPHgYlA6L+bkAFgPxz9vRlKzoCXsRyUszlQDtLlvCEJqdb/vucCAIp+9u9P4YWF1yA6FE4uK50xM9VD4Fv4keo7yd9clcK1tuivwThcLz8JL/eMWbftxXyag790HPdReyviWZWnbSIGcyuwH+HGRV7GyTg2QsxTF909iTU8cIZdrvxAd58/lY9yM1ovbUKYIe4HuK+5L9vWxEybuFQ3pvDP0yAtjxPnGTjBnrVGO/iWAJblaOYW/2EFN2ybWHxP0usrsjMZEKk8oYaZP2MkrB7MQfwmho+S9qqdcQ1gi2UjFRu+GFZ8X9OcmQRIjHg5gdmtZvhOUpWwddPXAozUcCw13kKBdBgtTKHGFrFkim5KJRjJEZVrIiAxGIe4=
  on:
    all_branches: true
